=== hyperledger-archives/composer/packages/composer-cli/lib/cmds/card/lib/schema/ccpschema.json
{
    "$schema" : "http://json-schema.org/schema#",
    "definitions" : {
        "client" : {
            "type" : "object",
            "properties" : {
                "organization" : { "type" : "string" }
            },
            "required" : [ "organization" ]
        },
        "certificateAuthorities" : {
            "type" : "object",
            "patternProperties": {
                "^.*$" : { "$ref": "#/definitions/certificateAuthority" }
            }
        },
        "certificateAuthority" : {
            "type" : "object",
            "properties": {
                "url" : { "format" : "uri" },
                "httpOptions" : { "$ref": "#/definitions/httpOptions" },
                "tlsCACerts" : { "$ref": "#/definitions/tlsCACerts" },
                "registrar" : { "$ref": "#/definitions/registrar" },
                "caName" : { "type" : "string" }
            },
            "required": [ "url" ]
        },
        "registrar" : {
            "properties": {
                "enrollId" : { "type" : "string" },
                "enrollSecret" : { "type" : "string" }
            },
            "required" : [ "enrollId", "enrollSecret" ]
        },
        "httpOptions" : {
            "type" : "object",
            "properties" : {
                "verify" : { "type" : "boolean" }
            }
        },
        "channels" : {
            "type" : "object",
            "patternProperties" : {
                "^.*$" : { "$ref": "#/definitions/channel" }
            },
            "minimum" : 1
        },
        "channel" : {
            "type" : "object",
            "properties" : {
                "orderers" : { "type" : "array" },
                "peers" : { "$ref" : "#/definitions/channel-peer" },
                "chaincodes" : { "type" : "array" }
            },
            "required" : [ "orderers", "peers" ]
        },
        "channel-peer" : {
            "type" : "object",
            "patternProperties": {
                "^.*$" : {
                    "endorsingPeer" : { "type" : "boolean" },
                    "chaincodeQuery" : { "type" : "boolean" },
                    "ledgerQuery" : { "type" : "boolean" },
                    "eventSource" : { "type" : "boolean" }
                },
                "additionalProperties": false
            },
            "minimum" : 1
        },
        "orderers" : {
            "type" : "object",
            "patternProperties": {
                "^.*$" : { "$ref": "#/definitions/orderer" }
            },
            "minimum": 1
        },
        "orderer" : {
            "type" : "object",
            "properties" : {
                "url" : { "format" : "uri" },
                "grpcOptions" : { "$ref": "#/definitions/grpcOptions" },
                "tlsCACerts" : { "$ref": "#/definitions/tlsCACerts" }
            },
            "required": [ "url" ]
        },
        "grpcOptions" : {
            "type" : "object",
            "properties": {
                "ssl-target-name-override" : { "type" : "string" },
                "grpc.max_send_message_length" : { "type" : "number" },
                "grpc.max_receive_message_length" : { "type" : "number" }
            }
        },
        "tlsCACerts" : {
            "type" : "object",
            "properties": {
                "pem" : { "type" : "string" },
                "path" : { "type" : "string" },
                "client" : { "$ref": "#/definitions/tlsCACertsClient" }
            }
        },
        "tlsCACertsClient" : {
            "type" : "object",
            "properties" : {
                "keyfile" : { "type" : "string"},
                "certfile" : { "type" : "string"}
            },
            "additionalProperties": false
        },
        "organizations" : {
            "type" : "object",
            "patternProperties": {
                "^.*$" : { "$ref": "#/definitions/organization" }
            },
            "minimum": 1
        },
        "organization" : {
            "type" : "object",
            "properties": {
                "certificateAuthorities" : { "type" : "array" },
                "mspid" : { "type" : "string" },
                "peers" : { "type" : "array" },
                "adminPrivateKey" : { "$ref": "#/definitions/adminPrivateKey" },
                "signedCert" : { "$ref": "#/definitions/signedCert" }
            },
            "required": [ "mspid", "peers" ]
        },
        "adminPrivateKey" : {
            "type" : "object",
            "properties": {
                "pem" : { "type" : "string" },
                "path": {
                    "type": "string"
                }
            },
            "oneOf" : [{
                "anyOf" : [{
                    "required" : ["path"]
                }, {
                    "required" : ["pem"]
                }
                ]
            }]
        },
        "signedCert" : {
            "type" : "object",
            "properties": {
                    "pem" : { "type" : "string" },
                    "path": {
                        "type": "string"
                    }
            },
            "oneOf" : [{
                "anyOf" : [{
                    "required" : ["path"]
                }, {
                    "required" : ["pem"]
                }
                ]
            }]
        },
        "peers" : {
            "type" : "object",
            "patternProperties": {
                "^.*$" : { "$ref": "#/definitions/peer" }
            },
            "minimum": 1
        },
        "peer" : {
            "type" : "object",
            "properties": {
                "url" : { "format" : "uri" },
                "eventUrl" : { "format" : "uri" },
                "grpcOptions" : { "$ref": "#/definitions/grpcOptions" },
                "tlsCACerts" : { "$ref": "#/definitions/tlsCACerts" }
            },
            "required": [ "url", "eventUrl"]
        }
    },
    "type" : "object",
    "properties" : {
        "name" : { "type" : "string" },
        "x-type" : { "enum" : [ "hlfv1" ] },
        "x-commitTimeout": { "type" : "number" },
        "version" : { "type" : "string", "pattern" : "^1.0.*$" },
        "client" : { "$ref" : "#/definitions/client" },
        "certificateAuthorities" : { "$ref": "#/definitions/certificateAuthorities" },
        "channels" : { "$ref" : "#/definitions/channels" },
        "orderers" : { "$ref" : "#/definitions/orderers" },
        "organizations" : { "$ref" : "#/definitions/organizations" },
        "peers" : { "$ref":  "#/definitions/peers" }
    },
    "required" : ["name", "x-type", "client", "certificateAuthorities", "channels", "orderers", "peers"]
}

=== hyperledger-archives/composer/packages/composer-tests-integration/profiles/basic-connection-org1.json
{
    "name": "hlfv1org1",
    "x-type": "hlfv1",
    "x-commitTimeout": 300,
    "version": "1.0.0",
    "client": {
        "organization": "Org1",
        "connection": {
            "timeout": {
                "peer": {
                    "endorser": "30s",
                    "eventHub": "30s",
                    "eventReg": "30s"
                },
                "orderer": "30s"
            }
        }
    },
    "channels": {
        "composerchannel": {
            "orderers": [
                "orderer.example.com"
            ],
            "peers": {
                "peer0.org1.example.com": {},
                "peer0.org2.example.com": {}
            }
        }
    },
    "organizations": {
        "Org1": {
            "mspid": "Org1MSP",
            "peers": [
                "peer0.org1.example.com"
            ],
            "certificateAuthorities": [
                "ca.org1.example.com"
            ]
        },
        "Org2": {
            "mspid": "Org2MSP",
            "peers": [
                "peer0.org2.example.com"
            ],
            "certificateAuthorities": [
                "ca.org2.example.com"
            ]
        }
    },
    "orderers": {
        "orderer.example.com": {
            "url": "grpc://localhost:7050"
        }
    },
    "peers": {
        "peer0.org1.example.com": {
            "url": "grpc://localhost:7051",
            "eventUrl": "grpc://localhost:7053",
            "grpcOptions": {
                "request-timeout": 300000
            }
        },
        "peer0.org2.example.com": {
            "url": "grpc://localhost:8051",
            "eventUrl": "grpc://localhost:8053",
            "grpcOptions": {
                "request-timeout": 300000
            }
        }
    },
    "certificateAuthorities": {
        "ca.org1.example.com": {
            "url": "http://localhost:7054",
            "caName": "ca.org1.example.com"
        },
        "ca.org2.example.com": {
            "url": "http://localhost:8054",
            "caName": "ca.org2.example.com"
        }
    }
}

=== hyperledger-archives/composer/packages/composer-cli/test/card/data/connection.in.doc.json
{
    "name": "hlfv1",
    "x-type": "hlfv1",
    "x-commitTimeout": 300,
    "version": "1.0.0",
    "client": {
        "organization": "Org1",
        "connection": {
            "timeout": {
                "peer": {
                    "endorser": "300",
                    "eventHub": "300",
                    "eventReg": "300"
                },
                "orderer": "300"
            }
        }
    },
    "channels": {
        "composerchannel": {
            "orderers": [
                "orderer.example.com"
            ],
            "peers": {
                "peer0.org1.example.com": {
                    "endorsingPeer": true,
                    "chaincodeQuery": true,
                    "ledgerQuery": true,
                    "eventSource": true
                }
            }
        }
    },
    "organizations": {
        "Org1": {
            "mspid": "Org1MSP",
            "peers": [
                "peer0.org1.example.com"
            ],
            "certificateAuthorities": [
                "ca.org1.example.com"
            ]
        }
    },
    "orderers": {
        "orderer.example.com": {
            "url": "grpc://orderer.example.com:7050"
        }
    },
    "peers": {
        "peer0.org1.example.com": {
            "url": "grpc://peer0.org1.example.com:7051",
            "eventUrl": "grpc://peer0.org1.example.com:7053"
        }
    },
    "certificateAuthorities": {
        "ca.org1.example.com": {
            "url": "http://ca.org1.example.com:7054",
            "caName": "ca.org1.example.com"
        }
    }
}
